const vlogs = [
    { title: "the video that got scrapped", url: "https://www.youtube.com/watch?v=5RNleXv8M-A&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=1&pp=iAQB" },
    { title: "I Let the Intrusive Thoughts Win", url: "https://www.youtube.com/watch?v=O_hhcrlqzVU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=2&pp=iAQB" },
    { title: "How Easy is it to move out of Japan?", url: "https://www.youtube.com/watch?v=nEiFP5ZIcds&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=3&pp=iAQB" },
    { title: "What to do in Tokyo?", url: "https://www.youtube.com/watch?v=bzog3YThUAU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=4&pp=iAQB" },
    { title: "This Restaurant Has Food You've Never Seen Before", url: "https://www.youtube.com/watch?v=hJjCJuHlBho&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=5&pp=iAQB" },
    { title: "I Hired an Artist to go to Girls Bars With Me", url: "https://www.youtube.com/watch?v=FYVaM3kG0cA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=6&pp=iAQB" },
    { title: "My Final Trip Outside of Tokyo", url: "https://www.youtube.com/watch?v=Ox21XKDXzSs&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=7&pp=iAQB" },
    { title: "The Problem with Daily Vlogging", url: "https://www.youtube.com/watch?v=XlE9QY32Xck&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=8&pp=iAQB" },
    { title: "How a Trash Taste Episode Gets Made", url: "https://www.youtube.com/watch?v=ieKczyPCDXo&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=9&pp=iAQB" },
    { title: "Getting Back on that Grind", url: "https://www.youtube.com/watch?v=LmrqPbUMshY&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=10&pp=iAQB" },
    { title: "I Became a CEO", url: "https://www.youtube.com/watch?v=e5AGi1sSJKE&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=11&pp=iAQB" },
    { title: "Day in the life of a CEO", url: "https://www.youtube.com/watch?v=7YUiQEcM2BA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=12&pp=iAQB" },
    { title: "Today's a short one", url: "https://www.youtube.com/watch?v=cqA2AMEyvv8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=13&pp=iAQB" },
    { title: "I Did Everything in Akihabara", url: "https://www.youtube.com/watch?v=x-V7vnzW6wk&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=14&pp=iAQB" },
    { title: "10 Things I Like and Dislike About Tokyo", url: "https://www.youtube.com/watch?v=DxFQ9Gdgh9M&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=15&pp=iAQB" },
    { title: "This Cafe in Tokyo is Only 3 Weeks Old", url: "https://www.youtube.com/watch?v=SSFGslVdxpM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=16&pp=iAQB" },
    { title: "What Are The Most Unique Tastes I Can Find in a Convenience Store", url: "https://www.youtube.com/watch?v=AoZEG2dANLM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=17&pp=iAQB" },
    { title: "The Most Touristy Thing I've Done in Tokyo", url: "https://www.youtube.com/watch?v=uAvOhbEx4Fw&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=18&pp=iAQB" },
    { title: "How Many Bars Can I Visit in Golden Gai in an Hour?", url: "https://www.youtube.com/watch?v=dXW4mkTGvTI&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=19&pp=iAQB" },
    { title: "There's a Fight Club in Shibuya", url: "https://www.youtube.com/watch?v=FOts3mlTsEo&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=20&pp=iAQB" },
    { title: "What to do in Tokyo as a Tourist (Odaiba)", url: "https://www.youtube.com/watch?v=W1F_bCdXUWo&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=21&pp=iAQB" },
    { title: "I Discovered The Best Bar in Tokyo", url: "https://www.youtube.com/watch?v=kXx0iDtFT48&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=22&pp=iAQB" },
    { title: "Getting to see What's Underneath Tokyo", url: "https://www.youtube.com/watch?v=ZyjzBGufvWc&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=23&pp=iAQB" },
    { title: "My Last Month in Japan", url: "https://www.youtube.com/watch?v=N69kkOblSoI&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=24&pp=iAQB" },
    { title: "Experiencing a Japanese Earthquake", url: "https://www.youtube.com/watch?v=WCW0n1dYJXY&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=25&pp=iAQB" },
    { title: "What to do in Tokyo as a Tourist (Asakusa)", url: "https://www.youtube.com/watch?v=wOXdc0tRpNI&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=26&pp=iAQB" },
    { title: "I Was Lied To Again...", url: "https://www.youtube.com/watch?v=72m-3JiPrxE&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=27&pp=iAQB" },
    { title: "This Building Has a Secret", url: "https://www.youtube.com/watch?v=WlFXiNV-TN4&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=28&pp=iAQB" },
    { title: "Getting my revenge", url: "https://www.youtube.com/watch?v=PNF3b9zzkrk&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=29&pp=iAQB" },
    { title: "My Last Challenge of the Year", url: "https://www.youtube.com/watch?v=8soiNVrdFXQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=30&pp=iAQB" },
    { title: "Exploring Japan's Nichest Hobby", url: "https://www.youtube.com/watch?v=iqglZtJt0H4&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=31&pp=iAQB" },
    { title: "Taking a VTuber to Unknown Japanese Bars", url: "https://www.youtube.com/watch?v=WWYtNCqAcNU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=32&pp=iAQB" },
    { title: "Testing Japan's Heat Tech", url: "https://www.youtube.com/watch?v=9YkS7kqKfhE&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=33&pp=iAQB" },
    { title: "Getting to see how Sumo Wrestlers Train", url: "https://www.youtube.com/watch?v=evmC7qOLqeY&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=34&pp=iAQB" },
    { title: "Unlimited Drinks for less than the Price of 2 Cocktails in America", url: "https://www.youtube.com/watch?v=Sc28CAP8rgM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=35&pp=iAQB" },
    { title: "Happy Holidays from Tokyo", url: "https://www.youtube.com/watch?v=OHfOIhGp6Ek&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=36&pp=iAQB" },
    { title: "Can I Make 4 Vlogs in a Day?", url: "https://www.youtube.com/watch?v=JKDn6lQ73_M&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=37&pp=iAQB" },
    { title: "The Ancient Japanese Art of Making Plastic Food", url: "https://www.youtube.com/watch?v=lt1lzFvaB5E&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=38&pp=iAQB" },
    { title: "I Did What You Asked...", url: "https://www.youtube.com/watch?v=YvwWmBrtiLk&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=39&pp=iAQB" },
    { title: "$1 vs $100 Japanese Meal", url: "https://www.youtube.com/watch?v=KOmAeEIaZK8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=40&pp=iAQB" },
    { title: "Getting to Visit the Temporary Pokémon Exhibition", url: "https://www.youtube.com/watch?v=yBw5fT_Nlvg&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=41&pp=iAQB" },
    { title: "I Bought a Vintage Camera in Akihabara", url: "https://www.youtube.com/watch?v=u8PExhE7Q1g&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=42&pp=iAQB" },
    { title: "This Event Has Won 3 Awards", url: "https://www.youtube.com/watch?v=oZJ31fUGsIQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=43&pp=iAQB" },
    { title: "One Trick to Find the Best Bars in Tokyo", url: "https://www.youtube.com/watch?v=kD7xrNEjHbE&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=44&pp=iAQB" },
    { title: "The Weirdest Museum in Tokyo", url: "https://www.youtube.com/watch?v=CyqLclEwc4U&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=45&pp=iAQB" },
    { title: "How to Properly Celebrate Christmas in Japan", url: "https://www.youtube.com/watch?v=kwyERJwUixw&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=46&pp=iAQB" },
    { title: "I Bought Tickets to Japan's Biggest Stationery Fair", url: "https://www.youtube.com/watch?v=AtdDONUyl3E&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=47&pp=iAQB" },
    { title: "Always Have a Second Plan", url: "https://www.youtube.com/watch?v=vV9gvo9iFu8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=48&pp=iAQB" },
    { title: "Today is a Mystery", url: "https://www.youtube.com/watch?v=ck0qJEAPHug&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=49&pp=iAQB" },
    { title: "Taking A 2 Hour Trip to Spain", url: "https://www.youtube.com/watch?v=eRtOSyVtxuw&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=50&pp=iAQB" },
    { title: "Surviving 24 Hours Only on Claw Machine Winnings", url: "https://www.youtube.com/watch?v=MXpHTBWfstU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=51&pp=iAQB" },
    { title: "Following a Pigeon for a Day", url: "https://www.youtube.com/watch?v=3VVUXu4pZFg&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=52&pp=iAQB" },
    { title: "Can You Experience Tokyo Without Drinking Any Alcohol?", url: "https://www.youtube.com/watch?v=jv8KOeH6mBQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=53&pp=iAQB" },
    { title: "Everything I Learned Living in Tokyo for 10 Months", url: "https://www.youtube.com/watch?v=BevFUxGtIAs&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=54&pp=iAQB" },
    { title: "Overcoming Tunnel Vision", url: "https://www.youtube.com/watch?v=DGbmG2-PBFM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=55&pp=iAQB" },
    { title: "I Have Now Visited Every Prefecture in Japan", url: "https://www.youtube.com/watch?v=GXTmwCQfhPg&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=56&pp=iAQB" },
    { title: "Accidentally entering a government facility", url: "https://www.youtube.com/watch?v=1sS_2ZixiUk&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=57&pp=iAQB" },
    { title: "I wouldn't break into someone's apartment, would I?", url: "https://www.youtube.com/watch?v=odYaXTJtrRY&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=58&pp=iAQB" },
    { title: "I took the JLPT and here's what happened", url: "https://www.youtube.com/watch?v=9oxjyTZ5kaE&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=59&pp=iAQB" },
    { title: "I Am Him", url: "https://www.youtube.com/watch?v=klArxrkJ7qo&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=60&pp=iAQB" },
    { title: "This Bar Will Change You as a Person", url: "https://www.youtube.com/watch?v=q5xK81t0KcU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=61&pp=iAQB" },
    { title: "It's Way Too Cold", url: "https://www.youtube.com/watch?v=JgH0iYue3nk&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=62&pp=iAQB" },
    { title: "My Life Is Not Interesting", url: "https://www.youtube.com/watch?v=2zvZsta-G8A&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=63&pp=iAQB" },
    { title: "My First Time Trying the Ninja Wire Experience", url: "https://www.youtube.com/watch?v=1vfpamY_3dA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=64&t=457s&pp=iAQB" },
    { title: "You Wanted Me to do this in Japan", url: "https://www.youtube.com/watch?v=byy1NbffTJM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=65&pp=iAQB" },
    { title: "Christmas Has Arrived in Tokyo", url: "https://www.youtube.com/watch?v=jVBGQMYvX8U&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=66&pp=iAQB" },
    { title: "Pranking my Editor", url: "https://www.youtube.com/watch?v=oCQ-JthLPuw&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=67&pp=iAQB" },
    { title: "The Impossible Photo Spot", url: "https://www.youtube.com/watch?v=Wq9UslMGvjU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=68&pp=iAQB" },
    { title: "My Favorite Show got a Cafe Adaptation", url: "https://www.youtube.com/watch?v=GpnEF5xLn0o&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=69&pp=iAQB" },
    { title: "Why I Don't Use Any Of This", url: "https://www.youtube.com/watch?v=O8d89CZwSKY&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=70&pp=iAQB" },
    { title: "How Long Should You Stay in Japan?", url: "https://www.youtube.com/watch?v=HMpAQ_i1o-c&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=71&pp=iAQB" },
    { title: "I Can't Keep Watching These Vloggers", url: "https://www.youtube.com/watch?v=tuWvbu6rZSw&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=72&pp=iAQB" },
    { title: "I Need to Slow Down", url: "https://www.youtube.com/watch?v=8hhbeFS5Ugc&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=73&pp=iAQB" },
    { title: "Could This Solve my Issues?", url: "https://www.youtube.com/watch?v=RnwJB0H0P1c&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=74&pp=iAQB" },
    { title: "How Hard is it To Make Chopsticks?", url: "https://www.youtube.com/watch?v=DQ9iZa6wIRk&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=75&pp=iAQB" },
    { title: "Trying The Most Traditional Japanese Alcohols", url: "https://www.youtube.com/watch?v=wbnbH3WBAVY&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=76&pp=iAQB" },
    { title: "The Biggest Regrets I Have Moving to Japan", url: "https://www.youtube.com/watch?v=yc1x98-U0Go&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=77&pp=iAQB" },
    { title: "Why Is This the Most Expensive Toilet in Japan?", url: "https://www.youtube.com/watch?v=SZ0INQiOR2E&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=78&pp=iAQB" },
    { title: "How Does This Keep Happening to Me", url: "https://www.youtube.com/watch?v=_mGXLD-ENzI&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=79&pp=iAQB" },
    { title: "I Don't Want to Put This in my Body", url: "https://www.youtube.com/watch?v=wjy2YAIoeMQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=80&pp=iAQB" },
    { title: "My Laptop Is About to Explode!", url: "https://www.youtube.com/watch?v=k9qqRXRNnfE&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=81&pp=iAQB" },
    { title: "You Should Steal", url: "https://www.youtube.com/watch?v=CYys2Fxl16Q&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=82&pp=iAQB" },
    { title: "I've Been Living In Japan for 9 Months Now...", url: "https://www.youtube.com/watch?v=DQ8OuAKZ9Fg&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=83&pp=iAQB" },
    { title: "A Day in the Life of a Japanese Bar Owner", url: "https://www.youtube.com/watch?v=aebsdKzvl5E&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=84&pp=iAQB" },
    { title: "It's Always a Struggle Against Time", url: "https://www.youtube.com/watch?v=FoIAFQCj1eg&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=85&pp=iAQB" },
    { title: "I Got Some News For You", url: "https://www.youtube.com/watch?v=ELEjWW9Z2BI&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=86&pp=iAQB" },
    { title: "I Didn't Think I'd Come Back Here...", url: "https://www.youtube.com/watch?v=4EGTDP7QdQc&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=87&pp=iAQB" },
    { title: "They Find Ways to Put Wagyu Inside Anything", url: "https://www.youtube.com/watch?v=pqlgclVg9sI&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=88&pp=iAQB" },
    { title: "This Video is Only For Millennials", url: "https://www.youtube.com/watch?v=4B3ACGk4S_o&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=89&pp=iAQB" },
    { title: "The Worst Yet Best Mountain To Visit in Tokyo", url: "https://www.youtube.com/watch?v=eWtJC-ZhLxM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=90&pp=iAQB" },
    { title: "Has Tokyo Cancelled Halloween?", url: "https://www.youtube.com/watch?v=qUdnpT0GNNc&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=91&pp=iAQB" },
    { title: "Do French Fries Get Better if you Age Them for 1 Year", url: "https://www.youtube.com/watch?v=t_KlfLjwoDg&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=92&pp=iAQB" },
    { title: "The Craziest Hobby in Japan", url: "https://www.youtube.com/watch?v=jakLNcR37xI&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=93&pp=iAQB" },
    { title: "100 Days Left", url: "https://www.youtube.com/watch?v=XWadwnE4qKM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=94&pp=iAQB" },
    { title: "Time to Make Some Improvements", url: "https://www.youtube.com/watch?v=PhCxzH7oqRA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=95&pp=iAQB" },
    { title: "Exploring the Tokyo Night Market As it is Meant to Be", url: "https://www.youtube.com/watch?v=0fr542MjppU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=96&pp=iAQB" },
    { title: "Trying My First Exoskeleton", url: "https://www.youtube.com/watch?v=oRcgG6QZY-0&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=97&pp=iAQB" },
    { title: "Naoshima: Japan's Hidden Art Island Paradise", url: "https://www.youtube.com/watch?v=WAadmdTs1qQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=98&pp=iAQB" },
    { title: "This Castle Offers Some Interesting Things", url: "https://www.youtube.com/watch?v=1f7P_6MYaZg&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=99&pp=iAQB" },
    { title: "The Final Most Disappointing Place in Japan", url: "https://www.youtube.com/watch?v=Y9prQ4nkVW0&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=100&pp=iAQB" },
    // Items 101–200 (previously added)
    { title: "Exploring the Japanese Scarecrow Village", url: "https://www.youtube.com/watch?v=iNWa3b2lh0o&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=101&pp=iAQB" },
    { title: "It's One of Those Days", url: "https://www.youtube.com/watch?v=dK81eXo85Qc&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=102&pp=iAQB" },
    { title: "Does the Size of the Item Match the Packaging", url: "https://www.youtube.com/watch?v=r4-4FrnFBNY&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=103&pp=iAQB" },
    { title: "Tokyo's Most Expensive District", url: "https://www.youtube.com/watch?v=-vdMymjNS2E&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=104&pp=iAQB" },
    { title: "Doing Every Dumb Thing You Asked Me", url: "https://www.youtube.com/watch?v=Wuad-ojFGgY&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=105&pp=iAQB" },
    { title: "I'm out of ideas", url: "https://www.youtube.com/watch?v=CqYtwonLm2s&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=106&pp=iAQB" },
    { title: "I Got The Car Back", url: "https://www.youtube.com/watch?v=JQ4m3kmpc60&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=107&pp=iAQB" },
    { title: "Getting Our Plans Cancelled Because of Toxic Fumes", url: "https://www.youtube.com/watch?v=ZimIJ3_6F-w&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=108&pp=iAQB" },
    { title: "This Volcano Erupted a Month Ago", url: "https://www.youtube.com/watch?v=jjlfjta65uc&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=109&pp=iAQB" },
    { title: "I Got Locked Out💀", url: "https://www.youtube.com/watch?v=fuk5MXgx2E8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=110&pp=iAQB" },
    { title: "Showing You Japan Through My Eyes", url: "https://www.youtube.com/watch?v=F-TsAZf8aBU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=111&pp=iAQB" },
    { title: "They Stopped the Train...", url: "https://www.youtube.com/watch?v=uQmwEMR2L4Y&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=112&pp=iAQB" },
    { title: "The Forbidden Blue Pool", url: "https://www.youtube.com/watch?v=34QnC5VNQHQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=113&pp=iAQB" },
    { title: "I'm Leaving Tokyo For a While...", url: "https://www.youtube.com/watch?v=wPoXFC_4Q6c&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=114&pp=iAQB" },
    { title: "It Has Been 8 Months Already...", url: "https://www.youtube.com/watch?v=GIxoYDkB6wM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=115&pp=iAQB" },
    { title: "The Things I'm Too Afraid to Try", url: "https://www.youtube.com/watch?v=I0ZZQOjPyoI&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=116&pp=iAQB" },
    { title: "just give up", url: "https://www.youtube.com/watch?v=PvN2UC4OR5U&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=117&pp=iAQB" },
    { title: "They Aired an Estonian Film Here", url: "https://www.youtube.com/watch?v=bcjaamCxYt8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=118&pp=iAQB" },
    { title: "Reviewing Japanese Autumn Foods", url: "https://www.youtube.com/watch?v=MXnBBirYSLA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=119&pp=iAQB" },
    { title: "Unlimited Sake for Only $6", url: "https://www.youtube.com/watch?v=aZ6u5EQKP4o&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=120&pp=iAQB" },
    { title: "Driving for 3 Hours and 40 Minutes Isn't Worth It", url: "https://www.youtube.com/watch?v=8dck3Wxaws0&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=121&pp=iAQB" },
    { title: "Why Are the Tourists Avoiding This Place?", url: "https://www.youtube.com/watch?v=UZ7bJlhm_OQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=122&pp=iAQB" },
    { title: "Doing This Becomes Illegal in 2 Days", url: "https://www.youtube.com/watch?v=EQO7CaNuf7Y&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=123&pp=iAQB" },
    { title: "I Could Barely Move", url: "https://www.youtube.com/watch?v=xqmswCQhJHM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=124&pp=iAQB" },
    { title: "The Turtle Donut", url: "https://www.youtube.com/watch?v=esGBEJTqFkc&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=125&pp=iAQB" },
    { title: "280 Year Old Mochi", url: "https://www.youtube.com/watch?v=HQladk5obeQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=126&pp=iAQB" },
    { title: "And Another One Done...", url: "https://www.youtube.com/watch?v=PDqVv6mMVSs&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=127&pp=iAQB" },
    { title: "This Theme Park isn't Good for your Wallet", url: "https://www.youtube.com/watch?v=3XNAv2UWjWs&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=128&pp=iAQB" },
    { title: "Doing Things I Couldn't Before", url: "https://www.youtube.com/watch?v=xsrlF_5_uHs&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=129&pp=iAQB" },
    { title: "The Giant Moon in Tokyo", url: "https://www.youtube.com/watch?v=7GMlYwtKp64&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=130&pp=iAQB" },
    { title: "I Rented a Japanese Man for a Day", url: "https://www.youtube.com/watch?v=qVfTW2WTmrU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=131&pp=iAQB" },
    { title: "A Talk in the Dark with my brother", url: "https://www.youtube.com/watch?v=mOal4M1Bfco&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=132&pp=iAQB" },
    { title: "A Talk in the Dark with Emirichu", url: "https://www.youtube.com/watch?v=W5vfhZnjr9U&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=133&pp=iAQB" },
    { title: "A Talk in the Dark with Dee Kirijo", url: "https://www.youtube.com/watch?v=zjgTJnU3l08&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=134&pp=iAQB" },
    { title: "A Talk in the Dark with Gigguk", url: "https://www.youtube.com/watch?v=l47zd5aNEz4&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=135&pp=iAQB" },
    { title: "A Talk in the Dark with Daidus", url: "https://www.youtube.com/watch?v=jOWEdl1b_wE&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=136&pp=iAQB" },
    { title: "Trying to Test Every Grade of Wagyu", url: "https://www.youtube.com/watch?v=rnm8z54yc3Q&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=137&pp=iAQB" },
    { title: "He Opened a Store in Tokyo", url: "https://www.youtube.com/watch?v=RscXDS3rjg4&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=138&pp=iAQB" },
    { title: "When a VTuber Gets to Touch Expensive Knives", url: "https://www.youtube.com/watch?v=Lt_4dH0AfXQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=139&pp=iAQB" },
    { title: "Tokyo at 5AM", url: "https://www.youtube.com/watch?v=woX_fXI7_2s&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=140&pp=iAQB" },
    { title: "There's an Amusement Park in the Middle of Tokyo", url: "https://www.youtube.com/watch?v=4-kaAOqb6eI&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=141&pp=iAQB" },
    { title: "This Ramen Restaurant Lost Their Michelin Star", url: "https://www.youtube.com/watch?v=BXSZZoS8Dpc&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=142&pp=iAQB" },
    { title: "This Bridge has a World Record", url: "https://www.youtube.com/watch?v=g75NVT8PIhw&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=143&pp=iAQB" },
    { title: "There's a Desert in the middle of Japan", url: "https://www.youtube.com/watch?v=oBD_P21xmKA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=144&pp=iAQB" },
    { title: "Everything I Discovered Living in Japan for 7 Months", url: "https://www.youtube.com/watch?v=-HMkK1eX8_4&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=145&pp=iAQB" },
    { title: "The Greatest Capybara Cafe in Tokyo", url: "https://www.youtube.com/watch?v=Txp9Xxt08No&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=146&pp=iAQB" },
    { title: "He Opened a Bar in Tokyo", url: "https://www.youtube.com/watch?v=8mS97-ifWfg&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=147&pp=iAQB" },
    { title: "Can I Speedrun Sapporo in 8 Hours?", url: "https://www.youtube.com/watch?v=so--cIOQnt0&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=148&pp=iAQB" },
    { title: "This is the most disappointing thing about Japan", url: "https://www.youtube.com/watch?v=HCBwslagG1c&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=149&pp=iAQB" },
    { title: "Let me tell you a story...", url: "https://www.youtube.com/watch?v=8TLrfu0LfJo&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=150&pp=iAQB" },
    { title: "Riding the Tokyo Metro for 100 Hours", url: "https://www.youtube.com/watch?v=OWsTQ_eKfkI&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=151&pp=iAQB" },
    { title: "Tokyo's Most Interesting Bar", url: "https://www.youtube.com/watch?v=03t6-muHE_k&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=152&pp=iAQB" },
    { title: "The Japanese Costco Experience", url: "https://www.youtube.com/watch?v=goYPgLfKyDc&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=153&pp=iAQB" },
    { title: "Behind the Scenes of a Crane Game Shoot", url: "https://www.youtube.com/watch?v=zIVrHEqS_x8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=154&pp=iAQB" },
    { title: "Is The Snoopy Museum Worth It?", url: "https://www.youtube.com/watch?v=ZcdsT5S787w&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=155&pp=iAQB" },
    { title: "What is in my Pocket?", url: "https://www.youtube.com/watch?v=bcA17RRDvYA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=156&pp=iAQB" },
    { title: "I'm Going Through Each and Every One...", url: "https://www.youtube.com/watch?v=Q-NP1F8BWvU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=157&pp=iAQB" },
    { title: "Day in the life of a VTuber", url: "https://www.youtube.com/watch?v=RDWe453taA0&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=158&pp=iAQB" },
    { title: "Getting a Free Limited Edition Gold Pokémon Medal", url: "https://www.youtube.com/watch?v=pMEQhCja0tA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=159&pp=iAQB" },
    { title: "The Only Reason I Went To Sendai...", url: "https://www.youtube.com/watch?v=fFzCRIyYQ08&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=160&pp=iAQB" },
    { title: "I Was Told to Eat This", url: "https://www.youtube.com/watch?v=W33St9igebQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=161&t=315s&pp=iAQB" },
    { title: "I Did It Again...", url: "https://www.youtube.com/watch?v=i0J64SAtoEM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=162&pp=iAQB" },
    { title: "5-Star vs 1-Star Melonpan Review", url: "https://www.youtube.com/watch?v=pcyqIukWQH4&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=163&pp=iAQB" },
    { title: "What If You Couldn't Walk", url: "https://www.youtube.com/watch?v=qc4ySp5rBLA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=164&pp=iAQB" },
    { title: "Visiting an Active Sewer System in Tokyo", url: "https://www.youtube.com/watch?v=15CspTx7wUQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=165&pp=iAQB" },
    { title: "Raw Dogging Mount Fuji", url: "https://www.youtube.com/watch?v=26bPBCw-GcM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=166&t=4s&pp=iAQB" },
    { title: "Do Not Visit This Store at 3AM", url: "https://www.youtube.com/watch?v=iRuYrkpligE&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=167&pp=iAQB" },
    { title: "This man films for Chris and Connor", url: "https://www.youtube.com/watch?v=uzjPRMbBBEY&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=168&pp=iAQB" },
    { title: "Taking Inspiration From the Small Things", url: "https://www.youtube.com/watch?v=9hMFM9zxsI0&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=169&pp=iAQB" },
    { title: "This Japanese Festival Isn't What I Expected...", url: "https://www.youtube.com/watch?v=Sm3G7hB5Zd8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=170&pp=iAQB" },
    { title: "Expensive Sushi vs. Cheap Sushi", url: "https://www.youtube.com/watch?v=7CKFZGo0_AQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=171&pp=iAQB" },
    { title: "How Busy is Japan's Biggest Convention", url: "https://www.youtube.com/watch?v=fGCPle5yhQE&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=172&pp=iAQB" },
    { title: "AI is Taking Everything From Us", url: "https://www.youtube.com/watch?v=DGSnIIf_PN0&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=173&pp=iAQB" },
    { title: "Take My Money", url: "https://www.youtube.com/watch?v=NItrOyyPa9g&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=174&pp=iAQB" },
    { title: "There Are Too Many Stops...", url: "https://www.youtube.com/watch?v=SLEGEJVn8r0&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=175&pp=iAQB" },
    { title: "It's Already the Halfway Mark", url: "https://www.youtube.com/watch?v=B2HLoB_AY-Y&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=176&pp=iAQB" },
    { title: "I Had to Speedrun Every Temple in Tokyo", url: "https://www.youtube.com/watch?v=okmIT7fMwNs&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=177&pp=iAQB" },
    { title: "24 Hours in the Tokyo Underground", url: "https://www.youtube.com/watch?v=xoSHkz9zLRo&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=178&pp=iAQB" },
    { title: "It's Way Too Hot", url: "https://www.youtube.com/watch?v=gI2z0i4ueIA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=179&pp=iAQB" },
    { title: "Is There Anything to do Around Mount Fuji?", url: "https://www.youtube.com/watch?v=xVXhBc-lXd8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=180&pp=iAQB" },
    { title: "Is Standing in Line Worth It?", url: "https://www.youtube.com/watch?v=OiiJaiqyQ_w&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=181&pp=iAQB" },
    { title: "Is DisneySea Better for Adults than Disneyland", url: "https://www.youtube.com/watch?v=GlViA-p_qtQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=182&pp=iAQB" },
    { title: "Reviewing Every Seasonal Sweet from 7-Eleven", url: "https://www.youtube.com/watch?v=9eR-mqupRrk&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=183&pp=iAQB" },
    { title: "Trying Out a Meme Bar", url: "https://www.youtube.com/watch?v=NI7FnagVpmo&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=184&pp=iAQB" },
    { title: "Going to a Japanese Clinic (Nothing's Wrong!)", url: "https://www.youtube.com/watch?v=YV2YAq1uoTU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=185&pp=iAQB" },
    { title: "Entering a Pokémon Stamp Rally", url: "https://www.youtube.com/watch?v=tgm0kgCyLEE&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=186&pp=iAQB" },
    { title: "In Japan, You Even Line Up for the Fireworks", url: "https://www.youtube.com/watch?v=QAoDjjJbg_4&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=187&pp=iAQB" },
    { title: "I Didn't Know You Could Get Scammed Like This in Tokyo", url: "https://www.youtube.com/watch?v=PMHhDVonZE4&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=188&pp=iAQB" },
    { title: "Japan During Rain is just So Fun!", url: "https://www.youtube.com/watch?v=zMtktKC1OiA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=189&pp=iAQB" },
    { title: "I Paid ¥2,000 to get a Picture with This Dog", url: "https://www.youtube.com/watch?v=EwaQs0hpCgw&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=190&pp=iAQB" },
    { title: "I Tried Japan's Craziest Noodle Challenge", url: "https://www.youtube.com/watch?v=J4e-c_dls5Y&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=191&pp=iAQB" },
    { title: "The Best Japanese Store That Tourists Don't Know Of", url: "https://www.youtube.com/watch?v=swb0ipGtNRc&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=192&pp=iAQB" },
    { title: "The Festival Dedicated to Traditional Japanese Crafts", url: "https://www.youtube.com/watch?v=H7uFymk9Y00&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=193&pp=iAQB" },
    { title: "The Closest Thing We Have to Westworld", url: "https://www.youtube.com/watch?v=TabOLuNCEQM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=194&pp=iAQB" },
    { title: "The Japanese Onsen Experience", url: "https://www.youtube.com/watch?v=-T2iniy8moI&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=195&pp=iAQB" },
    { title: "Failing at Making a Basic Japanese Dessert", url: "https://www.youtube.com/watch?v=vwJrLUZkQoo&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=196&pp=iAQB" },
    { title: "Walking 27km Through the Entirety of Tokyo", url: "https://www.youtube.com/watch?v=JqVL38k6OYA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=197&pp=iAQB" },
    { title: "Visiting 3 Weird Japanese Theme Bars", url: "https://www.youtube.com/watch?v=Yh1W6CFHjJQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=198&pp=iAQB" },
    { title: "He Was Ready For It", url: "https://www.youtube.com/watch?v=0Gx4m9pGeas&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=199&pp=iAQB" },
    { title: "Reviewing Japan's Moomin Park", url: "https://www.youtube.com/watch?v=X75IyTQetgY&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=200&pp=iAQB" },
    // New entries: items 201–361
    { title: "Cycling Around Tokyo's Artificial Island", url: "https://www.youtube.com/watch?v=IZel-pyTII0&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=201&pp=iAQB" },
    { title: "I Had To Use an Internet Cafe", url: "https://www.youtube.com/watch?v=rClZbaEWoqc&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=202&pp=iAQB" },
    { title: "Trying Out Japanese Cooling Products", url: "https://www.youtube.com/watch?v=Fg8UPTS2mVg&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=203&pp=iAQB" },
    { title: "Challenging my Babysitter in Crane Games", url: "https://www.youtube.com/watch?v=f9XUUCVw-V8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=204&pp=iAQB" },
    { title: "Everything I Learned Living in Tokyo For 5 Months", url: "https://www.youtube.com/watch?v=aE4fxU5XdG8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=205&pp=iAQB" },
    { title: "Giving Away $500 Worth of Literal Garbage at Anime Expo", url: "https://www.youtube.com/watch?v=yV0kMqFaBXo&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=206&pp=iAQB" },
    { title: "Unboxing $500 Worth of Literal Garbage from Anime Expo", url: "https://www.youtube.com/watch?v=nT7KvoxG11Q&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=207&pp=iAQB" },
    { title: "Cosplaying For The First Time at Anime Expo", url: "https://www.youtube.com/watch?v=2WRoO2ZwqT4&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=208&pp=iAQB" },
    { title: "We Don't Look The Same", url: "https://www.youtube.com/watch?v=Z_4NFcbc2Qg&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=209&pp=iAQB" },
    { title: "37 Hours of Pain", url: "https://www.youtube.com/watch?v=GQqnJQJrEsY&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=210&pp=iAQB" },
    { title: "The Important Things I Keep in my Backpack", url: "https://www.youtube.com/watch?v=Op524eyjZZ8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=211&pp=iAQB" },
    { title: "My Experience with the Fancy Soufflé Cake", url: "https://www.youtube.com/watch?v=vO8asW_AH3c&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=212&pp=iAQB" },
    { title: "The Most Expensive Instant Ramen I've Ever Eaten", url: "https://www.youtube.com/watch?v=K5bF6GqRW7E&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=213&pp=iAQB" },
    { title: "Visiting Tokyo's Piss Alley (it's hard to hold it in)", url: "https://www.youtube.com/watch?v=vtjuf1dqFoI&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=214&pp=iAQB" },
    { title: "Which Conbini Has The Best Fruit Sando?", url: "https://www.youtube.com/watch?v=He5LQBo9rNY&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=215&pp=iAQB" },
    { title: "How Expensive is it to Produce a Video for a VTuber?", url: "https://www.youtube.com/watch?v=1Vr0ejg2hBo&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=216&pp=iAQB" },
    { title: "The World's Largest Capsule Toy Store", url: "https://www.youtube.com/watch?v=LBtQDQDOHKQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=217&pp=iAQB" },
    { title: "What If You Only Had 1 Hour in Akihabara", url: "https://www.youtube.com/watch?v=-7MWLo7jOAI&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=218&pp=iAQB" },
    { title: "The Most Interesting Secondhand Store in Japan", url: "https://www.youtube.com/watch?v=RxojzWO3lhQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=219&pp=iAQB" },
    { title: "Can I Survive 24 Hours Only on Anime Foods", url: "https://www.youtube.com/watch?v=6fwQBxZ973U&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=220&pp=iAQB" },
    { title: "My First Idol Concert", url: "https://www.youtube.com/watch?v=JMrj8uU0CiE&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=221&pp=iAQB" },
    { title: "Why Do We Jump Over the Fire?", url: "https://www.youtube.com/watch?v=HNw3ucO5gqc&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=222&pp=iAQB" },
    { title: "This is the Face of a Killer!", url: "https://www.youtube.com/watch?v=g-gqPIUrF9g&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=223&pp=iAQB" },
    { title: "I Listened To My Comments", url: "https://www.youtube.com/watch?v=TdxKi_b1_aw&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=224&pp=iAQB" },
    { title: "What $60 in Okinawa Gets You", url: "https://www.youtube.com/watch?v=hndE-tDajhs&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=225&pp=iAQB" },
    { title: "I Tried the $325 Japanese Coffee", url: "https://www.youtube.com/watch?v=1_AwPpKMlrs&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=226&pp=iAQB" },
    { title: "Why I'm in Okinawa", url: "https://www.youtube.com/watch?v=ZY0TgkbvFUI&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=227&pp=iAQB" },
    { title: "Day in the Life of my Estonian Boyfriend", url: "https://www.youtube.com/watch?v=O_a3PjFYEvk&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=228&pp=iAQB" },
    { title: "Tokyo's Largest Supercar Meet Up Spot", url: "https://www.youtube.com/watch?v=NfP9Yfd18ug&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=229&pp=iAQB" },
    { title: "I Gave Them my Yu-Gi-Oh Card and They Made a Drink Out of It", url: "https://www.youtube.com/watch?v=1OEZGbTivCU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=230&pp=iAQB" },
    { title: "Getting the Full Abroad in Japan Studio Tour!", url: "https://www.youtube.com/watch?v=EbovkKgbZzQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=231&pp=iAQB" },
    { title: "Exploring the Abandoned Looking Vending Machine House", url: "https://www.youtube.com/watch?v=KpK_n1XcXic&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=232&pp=iAQB" },
    { title: "Getting Some Wagyu Okonomiyaki in Hiroshima", url: "https://www.youtube.com/watch?v=sT03uGSK0Os&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=233&pp=iAQB" },
    { title: "I Want to Pet It So Bad...", url: "https://www.youtube.com/watch?v=518c5doKUy8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=234&pp=iAQB" },
    { title: "5 Reasons Why You Should Go To Okayama", url: "https://www.youtube.com/watch?v=kBsXmWeFXQ8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=235&pp=iAQB" },
    { title: "12 Hours In Hiroshima  | 2 Must Try Travel Ideas", url: "https://www.youtube.com/watch?v=Kz2C6LnI0NE&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=236&pp=iAQB" },
    { title: "What If You're Burnt Out", url: "https://www.youtube.com/watch?v=cq53FwgEy88&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=237&pp=iAQB" },
    { title: "Trying Every Japanese Chocolate", url: "https://www.youtube.com/watch?v=k_e0KaJ5djA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=238&pp=iAQB" },
    { title: "I'm Not Telling You", url: "https://www.youtube.com/watch?v=XMde2iwAqS0&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=239&pp=iAQB" },
    { title: "Everything I Found Out Living in Japan for 4 Months", url: "https://www.youtube.com/watch?v=AU5pko4nba4&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=240&pp=iAQB" },
    { title: "Why Are My Viewers Going To This Bar?", url: "https://www.youtube.com/watch?v=ALybNh-8bCY&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=241&t=380s&pp=iAQB" },
    { title: "This is the Hotel To Rent When You Got That YouTube Money", url: "https://www.youtube.com/watch?v=bOmvLOnWbOo&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=242&pp=iAQB" },
    { title: "We Tried to Complete the Spartan Race", url: "https://www.youtube.com/watch?v=4xZSLQp76-A&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=243&pp=iAQB" },
    { title: "Going to an Expo Meant for Women", url: "https://www.youtube.com/watch?v=hcI2qltaquM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=244&pp=iAQB" },
    { title: "Reviewing Tokyo's Joypolis", url: "https://www.youtube.com/watch?v=O7e_2gPaS8A&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=245&pp=iAQB" },
    { title: "What Lies in the Asakusa Underground?", url: "https://www.youtube.com/watch?v=G5kjIdvdqsc&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=246&pp=iAQB" },
    { title: "They Control My Day", url: "https://www.youtube.com/watch?v=9EBOTpmWSzU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=247&pp=iAQB" },
    { title: "Will This Change How I Learn Japanese?", url: "https://www.youtube.com/watch?v=qXonDJYeE00&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=248&pp=iAQB" },
    { title: "is This Really Tokyo's \"Best\" Flea Market?", url: "https://www.youtube.com/watch?v=Ziu7NaPoDvw&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=249&pp=iAQB" },
    { title: "Exploring the Tokyo Night Market", url: "https://www.youtube.com/watch?v=EW-UfxvgRbQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=250&pp=iAQB" },
    { title: "This Museum is Run by Japan Tobacco...", url: "https://www.youtube.com/watch?v=dlpPXhEwdbg&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=251&pp=iAQB" },
    { title: "Trying Insect Ramen", url: "https://www.youtube.com/watch?v=F1NA7NS1Hbo&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=252&pp=iAQB" },
    { title: "Exploring an Abandoned Japanese Train Station with @SpillingTheMilk", url: "https://www.youtube.com/watch?v=fxtqwuMxEZo&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=253&pp=iAQB" },
    { title: "Let's Try Denim Ice Cream", url: "https://www.youtube.com/watch?v=ANLfGaQljtw&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=254&pp=iAQB" },
    { title: "Paying a Man to Speedrun Temples For Me", url: "https://www.youtube.com/watch?v=Fd9R_PYgC3w&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=255&pp=iAQB" },
    { title: "Reviewing a Random Park in Tokyo", url: "https://www.youtube.com/watch?v=dZRSdG1gBTg&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=256&pp=iAQB" },
    { title: "This is technically not clickbait", url: "https://www.youtube.com/watch?v=Ml11WewFwi0&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=257&pp=iAQB" },
    { title: "They Destroyed My Laptop lmao haha", url: "https://www.youtube.com/watch?v=owtK5rZwlrY&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=258&pp=iAQB" },
    { title: "Let This Man Show You Around Tokyo", url: "https://www.youtube.com/watch?v=q5IItj33t_Y&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=259&pp=iAQB" },
    { title: "This Was Not What I Expected", url: "https://www.youtube.com/watch?v=zs1qFyaLf30&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=260&pp=iAQB" },
    { title: "Trying the Japanese Batting Cages Didn't Go as Expected", url: "https://www.youtube.com/watch?v=BFoc3gW-Hkc&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=261&pp=iAQB" },
    { title: "The Set That GeexPlus Has Been Hiding From Us", url: "https://www.youtube.com/watch?v=TMe61s2-9sw&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=262&pp=iAQB" },
    { title: "He Delivers Curry to you on a Train", url: "https://www.youtube.com/watch?v=fzg1B2q9dP8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=263&pp=iAQB" },
    { title: "How to Record a YouTube Video in Japan", url: "https://www.youtube.com/watch?v=Nga7mCdwUwA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=264&pp=iAQB" },
    { title: "Day in the life of my Babysitter", url: "https://www.youtube.com/watch?v=7-l2PVcZNqQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=265&pp=iAQB" },
    { title: "You Made Me Visit 5 Quirky Japanese Bars", url: "https://www.youtube.com/watch?v=2q6PIVuaE1Q&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=266&pp=iAQB" },
    { title: "The Premium Cinema Experience Isn't Worth It", url: "https://www.youtube.com/watch?v=M186adYOjj4&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=267&pp=iAQB" },
    { title: "Everything's Broken", url: "https://www.youtube.com/watch?v=uE0WCyWMDBU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=268&pp=iAQB" },
    { title: "Everything I Discovered Living in Japan for 3 Months", url: "https://www.youtube.com/watch?v=GMw0kRVB2uU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=269&pp=iAQB" },
    { title: "The Samurai were really friendly", url: "https://www.youtube.com/watch?v=zlqC6mp5qpE&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=270&pp=iAQB" },
    { title: "The Most Expensive Cake I've Had in my Life", url: "https://www.youtube.com/watch?v=xa5ZsC3cV4M&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=271&pp=iAQB" },
    { title: "Can I Learn How To Read Japanese Through Manga", url: "https://www.youtube.com/watch?v=Dl8cpLW9W08&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=272&pp=iAQB" },
    { title: "Going to the Gym with a VTuber", url: "https://www.youtube.com/watch?v=hAJwzyFS0jU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=273&pp=iAQB" },
    { title: "What You've Been Asking For", url: "https://www.youtube.com/watch?v=Ac1NMWBWfn4&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=274&pp=iAQB" },
    { title: "The Most Expensive Amusement Park I've Ever Been To", url: "https://www.youtube.com/watch?v=ylaSyuMxVyM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=275&pp=iAQB" },
    { title: "We Tried Every Convenience Store Sake", url: "https://www.youtube.com/watch?v=6kROn4n9K_Q&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=276&pp=iAQB" },
    { title: "Going Back to Estonia", url: "https://www.youtube.com/watch?v=2CdN6Jdl5gU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=277&pp=iAQB" },
    { title: "These 4 Tiny Pieces of Kobe Beef Cost Me ¥1980", url: "https://www.youtube.com/watch?v=icMSO1__LCw&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=278&pp=iAQB" },
    { title: "Nara is Worth it Just For the Deer", url: "https://www.youtube.com/watch?v=QaFWUm9tmh4&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=279&t=398s&pp=iAQB" },
    { title: "Kyoto Has the Best Coffee I've Ever Had", url: "https://www.youtube.com/watch?v=tuoJ-qFf4YI&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=280&pp=iAQB" },
    { title: "The Vibes in Osaka are Different", url: "https://www.youtube.com/watch?v=VKNhdCmjsvc&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=281&pp=iAQB" },
    { title: "I Miss The Good Old Days", url: "https://www.youtube.com/watch?v=nIKUrUgQHD4&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=282&pp=iAQB" },
    { title: "The Best Things to do in Akihabara", url: "https://www.youtube.com/watch?v=VoLYVH88WEA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=283&pp=iAQB" },
    { title: "Should You Visit teamLab Borderless?", url: "https://www.youtube.com/watch?v=YP2KLYYvCsQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=284&pp=iAQB" },
    { title: "Showing Tourists What Tokyo Has to Offer", url: "https://www.youtube.com/watch?v=wwjCvEBR9qY&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=285&pp=iAQB" },
    { title: "What Is This Building in Tokyo?", url: "https://www.youtube.com/watch?v=zJkXHRHNnp0&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=286&pp=iAQB" },
    { title: "I Tried Making Japanese Fluffy Pancakes", url: "https://www.youtube.com/watch?v=rLog0FvvOWE&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=287&pp=iAQB" },
    { title: "The Greatest Dog Cafe in Tokyo", url: "https://www.youtube.com/watch?v=8S-NTYKhgnk&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=288&pp=iAQB" },
    { title: "Waiting 40 Minutes to see This Panda", url: "https://www.youtube.com/watch?v=Ej3Moqf_-KA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=289&pp=iAQB" },
    { title: "Testing a $39 Capsule Hotel", url: "https://www.youtube.com/watch?v=hiNTQs8kGwE&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=290&pp=iAQB" },
    { title: "They Did It!", url: "https://www.youtube.com/watch?v=GxO8NwDC_Zs&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=291&pp=iAQB" },
    { title: "10 Useless Facts About Sakura Trees", url: "https://www.youtube.com/watch?v=BlBsrFwG9_g&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=292&pp=iAQB" },
    { title: "Pranking Connor", url: "https://www.youtube.com/watch?v=oJsjrVyTR8Q&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=293&pp=iAQB" },
    { title: "This Cafe has a Hidden Bar Behind its Bookshelf", url: "https://www.youtube.com/watch?v=bFpfSNZj8is&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=294&pp=iAQB" },
    { title: "Meeting a Fellow Estonian in Japan", url: "https://www.youtube.com/watch?v=WCut92OI5Ak&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=295&pp=iAQB" },
    { title: "My Favorite Japanese Snacks", url: "https://www.youtube.com/watch?v=Tcky-vAIo1s&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=296&pp=iAQB" },
    { title: "Everything I've Been Through in my 2 Months of Living in Japan", url: "https://www.youtube.com/watch?v=BX7GiyTBgOY&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=297&pp=iAQB" },
    { title: "Getting Overrun by Little Piggies", url: "https://www.youtube.com/watch?v=oO9Cg9qGV4Y&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=298&pp=iAQB" },
    { title: "Reviewing Japan's Legoland", url: "https://www.youtube.com/watch?v=6eUr4PUPvfk&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=299&pp=iAQB" },
    { title: "My First Time at a Love Hotel", url: "https://www.youtube.com/watch?v=ySfh88A5fhY&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=300&pp=iAQB" },
    { title: "My Experience With Gyms in Japan", url: "https://www.youtube.com/watch?v=GugQnoBk7eM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=301&pp=iAQB" },
    { title: "I Tested the 1-Star Japanese Restaurant", url: "https://www.youtube.com/watch?v=xhNI8X41SHU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=302&pp=iAQB" },
    { title: "Getting to Row a Boat Between Sakura Trees", url: "https://www.youtube.com/watch?v=JO29zoy_X6Q&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=303&pp=iAQB" },
    { title: "The Capybara Onsen is Real!", url: "https://www.youtube.com/watch?v=Tg3tkl7Cfz4&t=332s&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=304&pp=iAQB" },
    { title: "Trying Chicago-Style Pizza in Tokyo", url: "https://www.youtube.com/watch?v=a1-ptO7Mebw&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=305&pp=iAQB" },
    { title: "10 Things I Like and Dislike About Tokyo", url: "https://www.youtube.com/watch?v=vr_GIVg4qT8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=306&pp=iAQB" },
    { title: "I Tried To Eat Every Sushi", url: "https://www.youtube.com/watch?v=pAUSp-QXIbg&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=307&pp=iAQB" },
    { title: "Visiting the Snake Cafe in Tokyo", url: "https://www.youtube.com/watch?v=19GSjLv5I-M&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=308&pp=iAQB" },
    { title: "Why Are There 333 Streamers at Tokyo Tower?", url: "https://www.youtube.com/watch?v=Sjj3I1E17Cc&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=309&pp=iAQB" },
    { title: "I Got To See Fishies!", url: "https://www.youtube.com/watch?v=UcmJ15RBmYE&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=310&pp=iAQB" },
    { title: "Getting My Ass Handed To Me...Again", url: "https://www.youtube.com/watch?v=vTwT_9NQ_m8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=311&pp=iAQB" },
    { title: "Almost Throwing Up at a Japanese Anime Convention", url: "https://www.youtube.com/watch?v=E8zUjoM0sGs&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=312&pp=iAQB" },
    { title: "Only Eating Sakura Products for 24 Hours", url: "https://www.youtube.com/watch?v=Hf895hy_Kgw&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=313&pp=iAQB" },
    { title: "Only Nerds Will Like This Video", url: "https://www.youtube.com/watch?v=fd-Uamu_QXk&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=314&pp=iAQB" },
    { title: "I Let Viewers Decide My Fate", url: "https://www.youtube.com/watch?v=XovS42zA7RM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=315&pp=iAQB" },
    { title: "You Can Let Your Stinky Little Grippers Out in this Bar", url: "https://www.youtube.com/watch?v=eNnS35QvNAI&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=316&pp=iAQB" },
    { title: "My Experience with the Pompompurin Cafe", url: "https://www.youtube.com/watch?v=DBhtLU6J9dA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=317&pp=iAQB" },
    { title: "I Took Him Out to get the Perfect Beer", url: "https://www.youtube.com/watch?v=mwejZ0xgy3U&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=318&pp=iAQB" },
    { title: "You Can Never Escape the Irish", url: "https://www.youtube.com/watch?v=jrrPRvWffvQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=319&pp=iAQB" },
    { title: "I Traveled 2 Hours to the Largest Convenience Store in Japan", url: "https://www.youtube.com/watch?v=8oltIXKaDVs&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=320&pp=iAQB" },
    { title: "You Can Get an Insane View of Tokyo for Free", url: "https://www.youtube.com/watch?v=ITFaxnJUZ0Y&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=321&pp=iAQB" },
    { title: "Going to a Bar I Found in my Comment Section", url: "https://www.youtube.com/watch?v=W1CaeNSRMZA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=322&pp=iAQB" },
    { title: "Trying To Speedrun Everything in Yokohama", url: "https://www.youtube.com/watch?v=Q3-zuIGW3vM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=323&pp=iAQB" },
    { title: "This is the 1 Trick to Min/Maxing Disneyland Tokyo", url: "https://www.youtube.com/watch?v=zIAeyQLoqZU&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=324&pp=iAQB" },
    { title: "The Best Pop-Up Cafe I've Ever Been To", url: "https://www.youtube.com/watch?v=KHQaOBJ1zq8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=325&pp=iAQB" },
    { title: "Every Other Booth at this Festival Offered Sake", url: "https://www.youtube.com/watch?v=4gPzY93PJcM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=326&pp=iAQB" },
    { title: "You Have 15 Minutes To Pet Bunnies", url: "https://www.youtube.com/watch?v=t82AD8dpWHQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=327&pp=iAQB" },
    { title: "Everything I Learned Living in Tokyo For 1 Month", url: "https://www.youtube.com/watch?v=jCi3I5lUV7w&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=328&pp=iAQB" },
    { title: "Trying Every Convenience Store Onigiri", url: "https://www.youtube.com/watch?v=ME3wW_PkSY8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=329&pp=iAQB" },
    { title: "What a $900 per Month Apartment in Tokyo Looks Like", url: "https://www.youtube.com/watch?v=I1AxZr0_QjA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=330&pp=iAQB" },
    { title: "I Survived the Biggest Ikea in Tokyo", url: "https://www.youtube.com/watch?v=AcovfGvbBbA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=331&pp=iAQB" },
    { title: "Renting Out an Entire Gym in Tokyo", url: "https://www.youtube.com/watch?v=syAZWgtCp5k&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=332&pp=iAQB" },
    { title: "This Mimosa Festival Was Not What I Thought...", url: "https://www.youtube.com/watch?v=HKOkNnxuEPw&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=333&pp=iAQB" },
    { title: "I Reviewed Trash Taste Sponsors", url: "https://www.youtube.com/watch?v=TaYrzG_URa0&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=334&pp=iAQB" },
    { title: "I Moved Again...", url: "https://www.youtube.com/watch?v=lp1EAl3d2kA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=335&pp=iAQB" },
    { title: "I Went to a Small Concert in Tokyo", url: "https://www.youtube.com/watch?v=EmXAmpaFkxI&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=336&pp=iAQB" },
    { title: "Entering a Random Building Every 500 Meters", url: "https://www.youtube.com/watch?v=9pMwPi8ZL0o&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=337&pp=iAQB" },
    { title: "Getting To See a VTubers Apartment", url: "https://www.youtube.com/watch?v=fHs1Q4ks3Rw&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=338&pp=iAQB" },
    { title: "Unlimited Desserts For $20", url: "https://www.youtube.com/watch?v=Hmqk9F5AZ-U&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=339&pp=iAQB" },
    { title: "We Tried Every Strong Zero", url: "https://www.youtube.com/watch?v=jrloE787wJQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=340&pp=iAQB" },
    { title: "Only Eating Balls For 24 Hours", url: "https://www.youtube.com/watch?v=lrdiqrPc04M&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=341&pp=iAQB" },
    { title: "Trying To Make Semla With Meilyne", url: "https://www.youtube.com/watch?v=iTUKxIk4GZA&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=342&pp=iAQB" },
    { title: "Interesting Things at the Strawberry Festival", url: "https://www.youtube.com/watch?v=cqrFyRBu0-0&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=343&pp=iAQB" },
    { title: "Expensive Fruit vs. Normal Fruit", url: "https://www.youtube.com/watch?v=b61k-lKBT8o&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=344&pp=iAQB" },
    { title: "Going For a Boat Ride in Tokyo", url: "https://www.youtube.com/watch?v=lFeJPVviDg0&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=345&pp=iAQB" },
    { title: "This Is Asia's Largest Miniature Museum", url: "https://www.youtube.com/watch?v=bmLxfNJttOs&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=346&pp=iAQB" },
    { title: "I Tried To Live Only On Vending Machines For 24 Hours", url: "https://www.youtube.com/watch?v=zt8Wqnin5f0&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=347&pp=iAQB" },
    { title: "Sometimes You Mess Up...", url: "https://www.youtube.com/watch?v=FOjaTefggBs&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=348&pp=iAQB" },
    { title: "Let's Try Fermented Soybeans!", url: "https://www.youtube.com/watch?v=yBrpaCIdhV0&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=349&pp=iAQB" },
    { title: "Why is it that Sports Gear in Japan Only Uses Foreigners for Advertisement?", url: "https://www.youtube.com/watch?v=d3WppTpWK2A&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=350&pp=iAQB" },
    { title: "How Easy is it to be Gluten Free in Japan", url: "https://www.youtube.com/watch?v=uIJEjG-OEZM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=351&pp=iAQB" },
    { title: "You Need To Buy This $20 Piece of Plastic If You Live in Japan", url: "https://www.youtube.com/watch?v=PM3wK7f9DoM&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=352&pp=iAQB" },
    { title: "This Exotic Animal Cafe Has Everything", url: "https://www.youtube.com/watch?v=1ecTvGZDVuk&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=353&pp=iAQB" },
    { title: "Visiting The Street in Tokyo That Banned Cars", url: "https://www.youtube.com/watch?v=G4eywjP-lx4&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=354&pp=iAQB" },
    { title: "Trying Every Japanese Health Potion", url: "https://www.youtube.com/watch?v=IZlEE6fHG5g&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=355&pp=iAQB" },
    { title: "What a $600 per Month Apartment in Tokyo Looks Like", url: "https://www.youtube.com/watch?v=GF6U-qtHjEQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=356&pp=iAQB" },
    { title: "I Stole a Monitor from Trash Taste", url: "https://www.youtube.com/watch?v=T6pc0XDA96s&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=357&pp=iAQB" },
    { title: "Visiting 3 \"Hidden\" Bars in Shinjuku", url: "https://www.youtube.com/watch?v=p6bA8rjVlv8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=358&pp=iAQB" },
    { title: "I Moved To Japan", url: "https://www.youtube.com/watch?v=RqMX-W3DXgs&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=359&pp=iAQB" },
    { title: "getting advice nobody asked for", url: "https://www.youtube.com/watch?v=uq9zNZjo7zY&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=360&pp=iAQB" },
    { title: "recording until my camera runs out of battery", url: "https://www.youtube.com/watch?v=tTWBQOqVAV8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=361&pp=iAQB" },
    // Final entries: items 362-368
    { title: "I Tried Fast Food Items that you Can't Get Outside of Japan", url: "https://www.youtube.com/watch?v=9p0QgCf8F4o&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=362&pp=iAQB" },
    { title: "nothing particular happened this day", url: "https://www.youtube.com/watch?v=O5BZLIoiBJg&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=363&pp=iAQB" },
    { title: "this is where I literally live", url: "https://www.youtube.com/watch?v=96IcVp4OwG0&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=364&pp=iAQB" },
    { title: "how to easily get rid of your trash in Japan", url: "https://www.youtube.com/watch?v=FHdylgwnaf4&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=365&pp=iAQB" },
    { title: "giving back the monitor that i \"acquired\"", url: "https://www.youtube.com/watch?v=oH7gnfH8_Ks&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=366&pp=iAQB" },
    { title: "A Day in the Life of Mudan", url: "https://www.youtube.com/watch?v=Z5xITiWFho8&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=367&pp=iAQB" },
    { title: "the end", url: "https://www.youtube.com/watch?v=zHPfkye7GVQ&list=PLrSx9zOYOPHFZEniDmIzKPEQK19PG4NAy&index=368&pp=iAQB" }

];

const randomButton = document.getElementById('randomButton');
const vlogCard = document.getElementById('vlogCard');
const vlogTitle = document.getElementById('vlogTitle');
const vlogLink = document.getElementById('vlogLink');

let shuffledVlogs = [...vlogs]; // Copy the original array
let currentIndex = 0;

// Shuffle the array using Fisher-Yates algorithm
function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
}

shuffleArray(shuffledVlogs);

function getNextVlog() {
    if (currentIndex >= shuffledVlogs.length) {
        alert("All vlogs have been shown! Refresh the page to start again.");
        return null;
    }
    return shuffledVlogs[currentIndex++];
}

function showVlog(vlog) {
    if (!vlog) return; // Stop if all vlogs have been shown

    vlogCard.classList.add('hidden');
    setTimeout(() => {
        vlogTitle.textContent = vlog.title;
        vlogLink.href = vlog.url;
        vlogCard.classList.remove('hidden');
    }, 300);
}

randomButton.addEventListener('click', () => {
    const nextVlog = getNextVlog();
    showVlog(nextVlog);
});